### ISSUE TITLE
Idea: Restart if unconnectable

### ISSUE THREAD

**Issue by beastlybeast** [royborgen/qbt_port_update#1]
Hi there, see this thread: https://github.com/qdm12/gluetun/issues/1882#issuecomment-2166744345

Basically it would be cool if, in this situation where the issue isn't the port number changing but qBittorrent just becoming unconnectable, that your tool could restart the container in that situation too.

**Comment by royborgen** [comment]
This is outside the scope of this projects, but what your trying to do can easily be solved: 
You can add healthcheck to your qBittorrent container by adding the following to you docker compose: 
```
   healthcheck:
      test: curl --fail -s http://localhost:8081/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
```
Restarting containers when healthcheck reports unhealthy can be done using another container: https://hub.docker.com/r/willfarrell/autoheal/

Optionally you can use docker swarm.
